import { v4 as uuid } from "uuid";
import { type Artwork, type TasteDimension, type TasteProfile, type User } from "./types";

export const tasteDimensions: TasteDimension[] = [
  "minimalism",
  "colorIntensity",
  "figurativeVsAbstract",
  "classicVsContemporary",
  "textureAffinity",
  "scalePreference",
  "riskAppetite",
  "warmVsCoolPalette",
  "narrativeDepth",
  "linearity",
  "collectorConfidence",
  "investmentIntent",
];

export const defaultTasteProfile: TasteProfile = tasteDimensions.reduce(
  (acc, key) => ({ ...acc, [key]: 50 }),
  {} as TasteProfile,
);

export const seedUser: User = {
  id: uuid(),
  email: "collector@artmatch.app",
  name: "Sample Collector",
  password: "password123",
  taste_profile: null,
  subscription_tier: "free",
  saved_artworks: [],
};

export const artworksSeed: Artwork[] = [
  {
    id: "work-1",
    title: "Screen Garden",
    artist: "Lena Voss",
    image_url: "/1.png",
    price_range: [14000, 18500],
    fair_value_score: 90,
    momentum_score: 82,
    medium: "Archival pigment print",
    dimensions: '52" × 76"',
    year: "2023",
    embedding: [0.82, 0.44, 0.58, 0.72, 0.63, 0.49],
    auction_comp: "Recent private transactions show stable pricing with low variance.",
    rationale: [
      "Strong narrative and editorial composition for statement spaces.",
      "Balanced risk profile for a first whole-asset acquisition.",
      "Above-average demand in contemporary photo-based works.",
    ],
  },
  {
    id: "work-2",
    title: "Chromatic Framework",
    artist: "Noah Imani",
    image_url: "/2.png",
    price_range: [12000, 16000],
    fair_value_score: 88,
    momentum_score: 77,
    medium: "Oil and casein on panel",
    dimensions: '50" × 38"',
    year: "2021",
    embedding: [0.76, 0.66, 0.37, 0.56, 0.71, 0.81],
    auction_comp: "Comparable geometric abstraction lots tightened by 4.1% YoY.",
    rationale: [
      "High compatibility with collectors preferring structure and line.",
      "Fair-value spread is narrow, signaling efficient pricing.",
      "Color cadence pairs well with modern interiors.",
    ],
  },
  {
    id: "work-3",
    title: "Signal Interior",
    artist: "Aya Mercier",
    image_url: "/3.png",
    price_range: [17500, 22500],
    fair_value_score: 91,
    momentum_score: 88,
    medium: "Mixed media on canvas",
    dimensions: '60" × 42"',
    year: "2022",
    embedding: [0.68, 0.73, 0.52, 0.61, 0.74, 0.78],
    auction_comp: "Placed slightly below median gallery comps across primary channels.",
    rationale: [
      "Balanced abstract vocabulary with collector-friendly scale.",
      "Momentum score reflects consistent exhibition cadence.",
      "Strong candidate for living-room hero placement.",
    ],
  },
  {
    id: "work-4",
    title: "Blue Stage Figure",
    artist: "Mira Chen",
    image_url: "/4.png",
    price_range: [11000, 14500],
    fair_value_score: 87,
    momentum_score: 74,
    medium: "Digital c-print",
    dimensions: '44" × 64"',
    year: "2022",
    embedding: [0.54, 0.91, 0.66, 0.69, 0.59, 0.83],
    auction_comp: "Contemporary figurative photo works show broad demand growth.",
    rationale: [
      "Distinct visual voice with strong narrative impact.",
      "Good fit for collectors with higher style risk appetite.",
      "Acquisition sits within practical first-collection budget bands.",
    ],
  },
  {
    id: "work-5",
    title: "Architectonic Drift",
    artist: "Ruben Hale",
    image_url: "/5.png",
    price_range: [15000, 21000],
    fair_value_score: 92,
    momentum_score: 86,
    medium: "Oil on canvas",
    dimensions: '58" × 48"',
    year: "2020",
    embedding: [0.74, 0.57, 0.48, 0.83, 0.77, 0.64],
    auction_comp: "Comparable large-format abstracts report low supply pressure.",
    rationale: [
      "Strong structural rhythm aligns with design-led collectors.",
      "Confidence interval is tight relative to segment average.",
      "Large format reads premium in open-plan homes.",
    ],
  },
  {
    id: "work-6",
    title: "Electric Veil",
    artist: "Sana Idris",
    image_url: "/6.png",
    price_range: [13000, 17000],
    fair_value_score: 86,
    momentum_score: 80,
    medium: "Acrylic and enamel",
    dimensions: '52" × 40"',
    year: "2024",
    embedding: [0.58, 0.89, 0.46, 0.72, 0.62, 0.88],
    auction_comp: "Primary-market allocations are filling quickly within 90 days.",
    rationale: [
      "Color intensity maps well to expressive taste profiles.",
      "Strong emerging momentum with manageable downside band.",
      "Works well in high-contrast interiors.",
    ],
  },
  {
    id: "work-7",
    title: "Quiet Mesh",
    artist: "Camille Ortiz",
    image_url: "/7.png",
    price_range: [9500, 12500],
    fair_value_score: 85,
    momentum_score: 73,
    medium: "Ink and graphite",
    dimensions: '36" × 36"',
    year: "2021",
    embedding: [0.88, 0.33, 0.41, 0.64, 0.82, 0.37],
    auction_comp: "Paper-based works maintain steady liquidity in online channels.",
    rationale: [
      "Minimalist expression with strong tonal discipline.",
      "Entry-level pricing for confident first acquisitions.",
      "Fits smaller wall footprints without losing presence.",
    ],
  },
  {
    id: "work-8",
    title: "Fragment Atlas",
    artist: "Dario Nkem",
    image_url: "/8.png",
    price_range: [15500, 20500],
    fair_value_score: 90,
    momentum_score: 85,
    medium: "Acrylic and charcoal",
    dimensions: '60" × 50"',
    year: "2023",
    embedding: [0.63, 0.71, 0.55, 0.79, 0.68, 0.74],
    auction_comp: "Multi-layer abstraction prices remain resilient through seasonal cycles.",
    rationale: [
      "Textural density aligns with high texture-affinity collectors.",
      "Fair-value band indicates healthy buy-side protection.",
      "Strong visual anchor for formal spaces.",
    ],
  },
  {
    id: "work-9",
    title: "Muted Current",
    artist: "Iris Petrov",
    image_url: "/9.png",
    price_range: [11500, 15000],
    fair_value_score: 84,
    momentum_score: 76,
    medium: "Gouache on linen",
    dimensions: '42" × 42"',
    year: "2019",
    embedding: [0.79, 0.48, 0.36, 0.58, 0.84, 0.45],
    auction_comp: "Comparable lots clear steadily with moderate spread.",
    rationale: [
      "Controlled palette supports long-term placement flexibility.",
      "Suitable for collectors preferring lower-volatility profiles.",
      "Strong fit for curated bedroom or study contexts.",
    ],
  },
  {
    id: "work-10",
    title: "Contour in Ochre",
    artist: "Lena Voss",
    image_url: "/contour-ocre.png",
    price_range: [16000, 19000],
    fair_value_score: 92,
    momentum_score: 84,
    medium: "Acrylic on linen",
    dimensions: '48" × 60"',
    year: "2021",
    embedding: [0.9, 0.2, 0.4, 0.7, 0.5, 0.3],
    auction_comp: "Comparable primary sales +2.8% spread in last 12 months.",
    rationale: [
      "Strong visual fit with warm-neutral interior palettes.",
      "Institutional exhibition cadence supports value resilience.",
      "Ideal first acquisition in $15k–$25k confidence band.",
    ],
  },
  {
    id: "work-11",
    title: "Field Signals",
    artist: "Noah Imani",
    image_url: "/dusk.png",
    price_range: [10000, 13000],
    fair_value_score: 88,
    momentum_score: 79,
    medium: "Pigment print",
    dimensions: '40" × 40"',
    year: "2020",
    embedding: [0.7, 0.5, 0.3, 0.4, 0.8, 0.6],
    auction_comp: "Edition velocity stable across two seasonal cycles.",
    rationale: [
      "Balanced geometry aligns to structured taste profile.",
      "Lower downside band for first-time online buyers.",
      "Compact format is room-flexible across urban layouts.",
    ],
  },
  {
    id: "work-12",
    title: "River Signal",
    artist: "Aya Mercier",
    image_url: "/quiet-frequency.png",
    price_range: [22000, 25000],
    fair_value_score: 94,
    momentum_score: 91,
    medium: "Mixed media on canvas",
    dimensions: '36" × 54"',
    year: "2022",
    embedding: [0.8, 0.9, 0.2, 0.5, 0.7, 0.9],
    auction_comp: "Below median placement versus recent gallery comps.",
    rationale: [
      "High signal for confident color-forward collectors.",
      "Strong artist momentum with museum acquisition tailwinds.",
      "Brokerage path includes insured logistics in quoted price.",
    ],
  },
  {
    id: "work-13",
    title: "Monolith Pulse I",
    artist: "Arman Lee",
    image_url: "/sculpture-1.png",
    price_range: [24000, 32000],
    fair_value_score: 93,
    momentum_score: 88,
    medium: "Cast bronze sculpture",
    dimensions: '22" × 18" × 16"',
    year: "2021",
    embedding: [0.72, 0.38, 0.67, 0.84, 0.91, 0.42],
    auction_comp: "Small-format bronzes saw increasing private demand this cycle.",
    rationale: [
      "Excellent fit for collectors open to first sculptural acquisition.",
      "Material durability supports long-term ownership confidence.",
      "Premium yet still within target whole-asset range.",
    ],
  },
  {
    id: "work-14",
    title: "Monolith Pulse II",
    artist: "Arman Lee",
    image_url: "/sculpture-2.png",
    price_range: [25000, 33500],
    fair_value_score: 92,
    momentum_score: 89,
    medium: "Cast bronze sculpture",
    dimensions: '24" × 18" × 18"',
    year: "2022",
    embedding: [0.69, 0.41, 0.71, 0.86, 0.93, 0.45],
    auction_comp: "Follow-up editions priced above prior release benchmark.",
    rationale: [
      "Continuity series with strong collector recognition.",
      "Above-average momentum score for contemporary sculpture segment.",
      "Works well in entryway and console staging contexts.",
    ],
  },
  {
    id: "work-15",
    title: "Arc Surface",
    artist: "Helena Kade",
    image_url: "/sculpture-3.png",
    price_range: [18500, 24500],
    fair_value_score: 89,
    momentum_score: 81,
    medium: "Resin and mineral composite",
    dimensions: '20" × 20" × 14"',
    year: "2023",
    embedding: [0.74, 0.52, 0.62, 0.78, 0.85, 0.57],
    auction_comp: "Primary-market waiting lists widened for related series.",
    rationale: [
      "Textural curvature appeals to organic-form preferences.",
      "Price range balances upside with first-buyer comfort.",
      "Complements neutral interiors with subtle depth.",
    ],
  },
  {
    id: "work-16",
    title: "Arc Surface Nocturne",
    artist: "Helena Kade",
    image_url: "/sculpture-4.png",
    price_range: [19500, 25500],
    fair_value_score: 90,
    momentum_score: 83,
    medium: "Patinated resin composite",
    dimensions: '21" × 20" × 15"',
    year: "2024",
    embedding: [0.62, 0.77, 0.64, 0.81, 0.83, 0.73],
    auction_comp: "New nocturne variant pricing shows disciplined premium.",
    rationale: [
      "High compatibility with collectors favoring dramatic tonality.",
      "Strong staging impact in low-light curated environments.",
      "Momentum supported by recent curated fair placements.",
    ],
  },
  {
    id: "work-17",
    title: "Orbit Chamber",
    artist: "Niko Barre",
    image_url: "/sculpture-5.png",
    price_range: [21000, 27500],
    fair_value_score: 91,
    momentum_score: 86,
    medium: "Polished steel and ceramic",
    dimensions: '26" × 17" × 17"',
    year: "2022",
    embedding: [0.67, 0.59, 0.69, 0.83, 0.88, 0.61],
    auction_comp: "Mixed-material sculpture lots outperform baseline category averages.",
    rationale: [
      "Strong material contrast for collectors with bold style appetite.",
      "Well-positioned fair-value confidence against peers.",
      "Museum-style presence in compact footprint.",
    ],
  },
  {
    id: "work-18",
    title: "Orbit Chamber Study",
    artist: "Niko Barre",
    image_url: "/sculpture-6.png",
    price_range: [16800, 22500],
    fair_value_score: 88,
    momentum_score: 84,
    medium: "Ceramic and powder-coated steel",
    dimensions: '20" × 15" × 15"',
    year: "2021",
    embedding: [0.71, 0.46, 0.57, 0.79, 0.86, 0.53],
    auction_comp: "Study editions remain liquid with moderate upside.",
    rationale: [
      "Accessible entry point into sculptural collecting.",
      "Good fit for collectors balancing aesthetics and value discipline.",
      "Versatile placement across shelves, pedestals, and consoles.",
    ],
  },
];
